name: qrpay
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=3.5.0 <4.2.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  # manually added dependency
  get: 4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts:
  country_code_picker: 3.1.0
  get_storage: ^2.1.1
  logger: 2.0.1
  pin_code_fields: 8.0.1
  intl: ^0.19.0
  image_picker: 1.0.4
  dotted_line: 3.2.3
  flutter_svg:
  hive_flutter:
  percent_indicator: ^4.2.4
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: 2.1.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^2.1.0
  awesome_snackbar_content: ^0.1.4
  smooth_page_indicator: ^1.1.0
  country_list_pick: ^1.0.1+1
  intl_phone_field: 3.2.0
  http: 1.1.0
  flutter_inappwebview: 6.1.5
  patterns_canvas: ^0.4.0
  flutter_html:
  share_plus: 10.1.2
  local_auth: 2.3.0
  cached_network_image: 3.3.1
  build_runner: ^2.4.13
  path_provider: ^2.1.1
  dropdown_search: ^6.0.2
  uuid:
  flutter_local_notifications: 17.2.4
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  qr_flutter: ^4.1.0
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.1.2
  dropdown_button2: ^2.3.9
  pusher_beams: ^1.1.1
  firebase_core: ^3.8.1
  win32: ^5.9.0
  rename_app: ^1.6.1
  restart_app: ^1.2.1
  shimmer: ^3.0.0

dependency_overrides:
  awesome_snackbar_content: 0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons:
  flutter_lints: 2.0.3


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
flutter:
  uses-material-design: true
  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/animation/
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/icon/wallet.svg
    - assets/logo/
    - assets/onboard/
    - assets/qr/
    - assets/ca/isrgrootx1.pem
